/*
 * This source file was generated by the Gradle 'init' task
 */
package megalomaniak;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestInstance.Lifecycle;

import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

@TestInstance(Lifecycle.PER_CLASS)
class AppTest {

    private MegalomaniakClient client;
    private MegalomaniakServer server;

    @BeforeAll
    public void setup() throws IOException {
        client = Megalomaniak.createClient();
        server = Megalomaniak.createServer();
    }

    @Test
    void callExistingEndpoint() {
        // client.CallEndpoint("/api/players", null);
    }

    @AfterAll
    public void tearDown() {

    }
}
