/*
 * This source file was generated by the Gradle 'init' task
 */
package megalomaniak;

public class App {
    public static void main(String[] args) {
        System.out.println("Starting Megalomaniak server...");
        MegalomaniakServer server = Megalomaniak.createServer();
        // server.Start();
        // System.out.println("Megalomaniak server started.");
    }
}
